### ISSUE TITLE
How to make chatterbot ask a series of questions when a particular intent is identified

### ISSUE THREAD

**Issue by adeete** [gunthercox/ChatterBot#1245]
I am using Python chatterbot. But Chatterbot is a kind of ask and tell model. It was like- the first statement is question and the next statement is the answer for it. But I want my chatterbot to ask a series of questions when it is related to a particular intent. For example if the person comes up asking about pizza then first the chatterbot will ask "what kind of pizza do you want?". After the user replies the bot will be asking about the add on etc. 
Can anyone please suggest any algorithm or any library in chatterbot to implement this functionality?

**Comment by vkosuri** [comment]
Sure, This could be possible, If you write your [own logic adapter](http://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html). Instead you could try with existing stuff  also.

Right now i don't have full written example, I think the below a pseudo code that work for you 

``` YAML
categories:
- pizza query
conversations:
- - what kind of pizza do you want?
  - You are order Medium pan successfully place.
```

``` YAML
categories:
- pizza order
conversations:
- - can you place order for me?
  - Med
```

``` Python
chatbot.response.categories in 'pizza query':
      do_your_operation()
```
