### ISSUE TITLE
help

### ISSUE THREAD

**Issue by patatetom** [gunthercox/ChatterBot#1953]
hello,

a little help and some answers would be welcome.

I'm trying to set up an automaton that guides the user to the right place.
before presenting you the used set, here's the problem right away:

```diff
+ hello
+ hello, I'm ChatterBot, on which application can I help you ?
+ scoobidoo            
+ I don't understand your question, which application can I help you with ?
+ app1
+ what problem are you having with app1 ?
+ password
- I don't understand your question, which application can I help you with ?
+ change password
- I don't understand your question, which application can I help you with ?
+ change my password
+ to change your password, click on http://app1.reset.my.password/
+ app2
+ what problem are you having with app2 ?
+ change my password
- to change your password, click on http://app1.reset.my.password/
+ hello
+ hello, I'm ChatterBot, on which application can I help you ?
+ app2
+ what problem are you having with app2 ?
+ change my password
- to change your password, click on http://app1.reset.my.password/
+ still not working
- in this case, contact 0000-123-456
```

the automaton doesn't take into account the previous answer : how to solve this problem?

moreover,
- how to avoid systematic updating of nltk data ?
- what is the keyword `categories` in the yml files, what is their purpose?
- what does the `sentence_tokenizer.pickle` file created once the training is done correspond to?

```console
[nltk_data] Downloading package averaged_perceptron_tagger to nltk_data..
[nltk_data]   Package averaged_perceptron_tagger is already up-to-date!
[nltk_data] Downloading package stopwords to nltk_data..
[nltk_data]   Package stopwords is already up-to-date!
```

here's what I use :

```console
$ tree
.
├── chat.py
├── coach.py
└── coaching
    ├── app1.yml
    ├── app2.yml
    └── greetings.yml
1 directory, 5 files
```

```console
$ cat coaching/greetings.yml 
```

```yml
categories:
- greetings
conversations:
- - hello
  - hello, I'm ChatterBot, on which application can I help you ?
- - hi
  - hello, I'm ChatterBot, on which application can I help you ?
- - bye
  - goodbye, I hope I've lived up to your expectations
- - good bye
  - goodbye, I hope I've lived up to your expectations
- - app1
  - what problem are you having with app1 ?
- - app2
  - what problem are you having with app2 ?
```

```console
$ cat coaching/app1.yml 
```

```yml
categories:
- app1
conversations:
- - I would like to change my password
  - to change your password, click on http://app1.reset.my.password/
- - it's still not working
  - in this case, contact 0000-123-456
```

```console
$ cat coaching/app2.yml 
```

```yml
categories:
- app2
conversations:
- - I would like to change my password
  - to change your password, click on http://app2.reset.my.password/
- - it's still not working
  - in this case, contact 1111-456-123
```

(the links and phone numbers are not the same)

```console
$ cat coach.py
```

```python
from chatterbot import ChatBot
chat = ChatBot(
	"chat",
	database_uri = "sqlite:///chat.db",
)
from chatterbot.trainers import ChatterBotCorpusTrainer
coach = ChatterBotCorpusTrainer(chat)
coach.train("./coaching/")
```

```console
$ python coach.py 
[nltk_data] Downloading package averaged_perceptron_tagger to nltk_data..
[nltk_data]   Package averaged_perceptron_tagger is already up-to-date!
[nltk_data] Downloading package stopwords to nltk_data..
[nltk_data]   Package stopwords is already up-to-date!
Training app1.yml: [####################] 100%
Training app2.yml: [####################] 100%
Training greetings.yml: [####################] 100%
```

```console
$ tree
.
├── chat.db
├── chat.py
├── coach.py
├── coaching
│   ├── app1.yml
│   ├── app2.yml
│   └── greetings.yml
└── sentence_tokenizer.pickle
1 directory, 7 files
```

```console
$ cat chat.py
```

```python
from chatterbot import ChatBot
chat = ChatBot(
	"chat",
	database_uri = "sqlite:///chat.db",
	default_response = "I don't understand your question, which application can I help you with ?",
	read_only = True,
)
while True:
    try:
        question = input()
        response = chat.get_response(question)
        print(response)
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

```console
$ python chat.py
[nltk_data] Downloading package averaged_perceptron_tagger to nltk_data..
[nltk_data]   Package averaged_perceptron_tagger is already up-to-date!
[nltk_data] Downloading package stopwords to nltk_data..
[nltk_data]   Package stopwords is already up-to-date!
hello
hello, I'm ChatterBot, on which application can I help you ?
scoobidoo            
I don't understand your question, which application can I help you with ?
app1
what problem are you having with app1 ?
password
I don't understand your question, which application can I help you with ?
change password
I don't understand your question, which application can I help you with ?
change my password
to change your password, click on http://app1.reset.my.password/
app2
what problem are you having with app2 ?
change my password
to change your password, click on http://app1.reset.my.password/
hello
hello, I'm ChatterBot, on which application can I help you ?
app2
what problem are you having with app2 ?
change my password
to change your password, click on http://app1.reset.my.password/
still not working
in this case, contact 0000-123-456
^C
```
