### ISSUE TITLE
tagging training data

### ISSUE THREAD

**Issue by 01X2** [gunthercox/ChatterBot#2203]
Hey, I'm working with training from multiple .yml files and was wondering if there was a way to access the category/file that the response was retrieved from? For example:

`greetings.yml`
```yaml
---
category:
- greetings
conversations:
- - hey
  - Hi
  - how are you
  - not bad
```

`personalQuestions.yml`
```yaml
---
category:
- other
conversations:
- - whats your favourite colour
  - blue
```

and then in the main file:
`main.py`
```py
response = chatbot.get_response('whats your favourite colour')

#
# Is there somehow a way to access "personalQuestions" since it was the file in which the response was retrieved from?
#

```

Thanks~
