### ISSUE TITLE
Modify ChatterBot Corpus trainer to save corpus categories as tags for statements

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#924]
This is a small change that needs to be made before future changes that will help improve the time and processing efficiency when ChatterBot generates a response to an input statement.

Changes have already been made to add categories to the [ChatterBot Corpus](https://github.com/gunthercox/chatterbot-corpus/) so that the data looks like this:

```yaml
categories:
- conversations
conversations:
- - Good morning, how are you?
  - I am doing well, how about you?
  - I'm also good.
  - That's good to hear.
  - Yes it is.
- - Hello
  - Hi
  - How are you doing?
  - I am doing well.
```

The `categories` attribute allows a list of descriptive labels to be added to the collection of dialog. Now, changes need to be made so that the `ChatterBotCorpusTrainer` in [trainers.py](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py) adds the values from the `categories` list in the corpus data to the `tags` fields that statements have.

***

In the future (a different issue and pull request will be created to describe and make this change), the categorization of statements will make it possible for the chat bot to predict a smaller set of data that a possible response should be likely to exist it.
